### ISSUE TITLE
help please ^^

### ISSUE THREAD

**Issue by anso3000** [Miei/battle-notify#2]
> [dispatch] handle: failed to parse S_SPAWN_USER<2>
hook: <unknown> @ battle-notify-master
error: no definition found for message (name: "S_SPAWN_USER", code: 59340, version: 2)

Data:
ce01cce7000000000100c601060112012a0136012

What are the module commands?

**Comment by wuaw** [comment]
You need to update `tera-proxy` and it's dependencies, you are missing some new packet definitions.

There are no module commands, everything is configured in the `config` folder. 

I haven't made any documentation because the module is a work in progress and I haven't settled completely on the names for some event types. So for now, you'll have to follow by example of the existing config files to create your own events.
